### ISSUE TITLE
[iOS] If system time is 2 hours or more in the past relative to the real time "Certificate issuance date is in the future is shown"

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#100]
1. Misleading error message "Certificate issuance date is in the future is shown" if system time is set to at least two hours in the past. 
2. Currently the iOS and Android behaviours differ from each other by the message shown.

Given the attached valid VAC Certificate is scanned with iOS Device set to >=2 hour in the past relative to the actual real time, the Error "Certificate issuance date is in the future is shown".  

This is misleading and the actual error should be "Cryptographic signature invalid" as it is the case with the Android version. 

## Expected behaviour

1. Set device time to at least 2 hours in the past;
2.  Scanned attached VAC Certificate

## Technical details
iPhone 8 plus v. Lutz, iOS 14.4
iOS Verifier App 1.1.5 -tst (2)
![IMG_20210708_122007](https://user-images.githubusercontent.com/76050122/124910103-7ea54100-dfeb-11eb-9a46-d128272140e6.jpg)

![VAC_01_Juni](https://user-images.githubusercontent.com/76050122/124907990-1d7c6e00-dfe9-11eb-95a2-59ddf8ba2d0a.jpg)

**Comment by alexchornyi** [comment]
@RalicaY Fixed, please take a look in next build.

**Comment by RalicaY** [comment]
Successfully retested iOS Verifier 1.1.6 (4)
