### ISSUE TITLE
[iOS] Scanning a certificate, created with a not supported Schema-Version does not result in INVALID as expected 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#103]
![version2 0 json](https://user-images.githubusercontent.com/76050122/125250008-152c7780-e2f6-11eb-9a0a-03cc94913fc9.png)

## Describe the bug

Given the certificate with a higher Version 2.0.0 than the current, scanning it should result in INVALID.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by Hendrik-Schmidt-Schierhorn-TSI** [comment]
The reason for this behaviour is, that the Schema-Version is colliding with the Business-Rules. That leads to rules with the state "open".
The Code itself can be read and is valid, so we should not show the Invalid-Screen.

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY @ltranvan  I will close this issue due to Hendriks comments.
