### ISSUE TITLE
iOS - Verifier App didn't check the HC1 prefix in QR Code

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-ios#105]
**Describe the bug**
According to the hight prio issue for iOS that the HC1 prefix is removed in the resultant QR Code in Wallet app
eu-digital-green-certificates/dgca-app-core-ios#83

we found out that the verifier apps didnt check the HC1 prefix.

The QR Code with no HC1 prefix is scanned by the verifier app as valid but should be invalid.

**Expected behaviour**
The QR Code with no HC1 prefix iis invalid.

QR Code from iOS wallet ACC
![image](https://user-images.githubusercontent.com/81565834/125974651-96e51a08-a6fb-401a-8d41-2e54e0aa0c3d.png)

QR Code : 6BFOXN%TSMAHN-HR S7OQLQ7P:I/F8/R8PJE2FC$K9J2T5DO:.IEHEUD7EP4R1BF/8XG-O9UVPQRHIY1+ HNQ1 WUQRELS400TXRVJR2B+2D-4Q/S6ALIHRV%Q0U0NK7GMV /KI-KO5L$W20YC9Y4KCTWZK/SNKV0ADF9Y4.$S6ZC0JB3I3KD38D0MJC7ZSA KZU0I1-I0OC6H0/VMNPM Q5TM8N9-I06H00YQKR3T3+7A.N88J4R$F/MAITH-+R2YBV44PZB6H0CJ0%H0%P8C K1U70%KLR2C KPLIUM42CGCHGL%5%DBF.7F.OZJJ.V47NV/HLSY4L8S1JPTQNZEFHAPDZISP42DS9DU0CEBQ/GXQF8$G5LBYDNOOV+QJW774338Q0V77$OFI6H:Q8:Q8797W0H2DNL87-VOZE32ORAUQET-QIY+I23D47QD.V7M2OTXNIYDKO3E9$2 IAS.LEO40R2-7RQESPNFNHEHQCZS:M2D+L9 M$1LT185.2YSC9QN20QB6K1

**Comment by ltranvan** [comment]
It is decided in the Call 13:30 today that this is a feature of the verifier app and there is no requirement for the verifier to check the HC1 prefix. Therefore it is not a bug and the ticket can be closed.

**Comment by kerstin-oppermann-tsi** [comment]
@ltranvan in which call this was descided? Today morning in our daily call we decided that this has to be fixed in both apps. And Android already has an PR for this feature.
