### ISSUE TITLE
iOS - QR Codes with region codes should not be checked for business rules

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-ios#106]
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/validation4/AT/1.3.0/TEST.png
https://github.com/eu-digital-green-certificates/dcc-quality-assurance/blob/validation4/AT/1.0.0/VAC.png

Both codes from Austria contain the region flag. As I understand these codes should be filtered out for checking business rules. In Android this is the fact in iOS is not. Please contact with @Hendrik-Schmidt-Schierhorn-TSI and @oleksandrsarapulovgl for handling this issue.

Extract from Emails regarding to this:
@oleksandrsarapulovgl wrote:
_The problem is that rules being returned for Austria contain the region "AT". For example:: https://dgca-businessrule-service.cfapps.eu10.hana.ondemand.com/rules/at/a02033dca7603faeddda8a957074a4bb942e98e3c5128f3664044ec64802217a. That's why we filter it out as agreed with Steffen.
So, it's either a bug on the iOS side, or bug on the BE side or updated requirements. We need either to remove regions from Austrian rules on the BE side. Or update iOS to properly filter rules out. Or, probably we need to relax filtering on the Android side. But I implemented it the way confirmed with Steffen._

Milan wrote:
_Would you please
•	make sure the iOS version behaves the same as the Android version. To my understanding this means filtering the rules out containing a region specification. (@Hendrik)
•	tell me whether AT’s rules conform to the specification and if not, how they need to be modified? Removing the region field altogether, providing null or string.empty in that field? (@Oleksandr/@Hendrik)_

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi please check on latest version of app

**Comment by kerstin-oppermann-tsi** [comment]
@alexchornyi with verifier app from 10th august 1.1.6.1 the country rules are check for the codes. And this should no be according to spec. Because these are codes with region codes as I understood. 
The Android app handles these codes correctly and do not check for country rules.
@Hendrik-Schmidt-Schierhorn-TSI

**Comment by alexchornyi** [comment]
fixed
