### ISSUE TITLE
iOS Verifier - Share Button in Debug Mode is available for Valid Certificates, should be visible only in emergency mode

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#114]
## Describe the bug

The option to share data in debug mode is available not only for certificates which are invalid or with limited validity, but also -- for valid certificates (i.e. NOT only for emergency cases).  Quote from chap. 8.2 of the spec: "_This feature should be enabled **only** in emergency cases."_

## Expected behaviour

Valid certificates should not have the share-option in debug mode. 

## Steps to reproduce the issue
1. Scan a valid certificate in debug mode.
2. Certificate is valid and the "share" button is available.

## Technical details
iOS Verifier 1.2.0.1 
iPhone 8 plus v. Lutz, iOS 14.4
![IMG_20210928_131212](https://user-images.githubusercontent.com/76050122/135077274-631fd0b5-5920-41df-a724-5fbd3c72bd69.jpg)

**Comment by kerstin-oppermann-tsi** [comment]
retested successfully in release 1.2.3.1.(11)
