### ISSUE TITLE
[iOS] Broken rule should yield "open", not "false"

### ISSUE THREAD

**Issue by chrloch** [eu-digital-green-certificates/dgca-verifier-app-ios#116]
## Description

When a rule is broken (e.g. features an undefined variable), the verifier app on iOS yields a failed status for this rule. 

## Expected behaviour

The status of the rule should be OPEN (as it is in the Android version)

## Steps to reproduce the issue

This can be reproduced scanning a valid vaccination DCC and verifying for Switzerland.
VR-CH-0004 and VR-CH-0006 contain a reference to "var":"external.validationClockAtStartOfDay" which does not exist. 

## Technical details

Reproduced with ACC backend

**Comment by kerstin-oppermann-tsi** [comment]
@chrloch any idea how to test this issueon an other way? The reference to "var":"external.validationClockAtStartOfDay" doesn't exist in the Switzerland Rules (on ACC)

**Comment by chrloch** [comment]
I can create a broken rule for the DX country again.

**Comment by kerstin-oppermann-tsi** [comment]
This would be good when @ihorkhomyak or @ivlasov implemented a fix for that issue.

**Comment by kerstin-oppermann-tsi** [comment]
@chrloch can you retest this issue or provide a broken rule for testing

**Comment by chrloch** [comment]
I don't have an iOS device but I have created a broken rule to become effective in two days: 
[rule service acc] /rules/DX/2b77f485a984ae9fb52a14b8ba4bf52948f9948c6a6bf3b3d0c15f052b7b6263

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/142214223-aa124a0f-e4b2-41ae-8a2c-4426f52969eb.png)
Seems issue is fixed now with verifier 1.2.3.1(12)
