### ISSUE TITLE
PRIO 1 - iOS Verifier - Certificates have allways issues with business rules and opening the rules leads to crash

### ISSUE THREAD

**Issue by Hendrik-Schmidt-Schierhorn-TSI** [eu-digital-green-certificates/dgca-verifier-app-ios#119]
## Describe the bug

 Certificates that should be green (vaccination 2/2, and more than 14 days ago) lead to the "limited validity screen". When opening the list of business rules, the app crashes.

## Technical details

- App-Version 1.2.3.1 (8) [ACC]
- iPhone X
- iOS 14.1

![ACC_MC_TestCert_Vac2](https://user-images.githubusercontent.com/81570419/140103345-b5dea538-5210-4cea-b90c-55a37a6de4c0.JPG)

**Comment by kerstin-oppermann-tsi** [comment]
same for TST certificates

**Comment by kerstin-oppermann-tsi** [comment]
fixed

**Comment by kerstin-oppermann-tsi** [comment]
retested successfully in release 1.2.3.1.(11)
