### ISSUE TITLE
iOS - Verifier - on iPad verifier app should not be able to rotate

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-ios#122]
When I rotate my device (iPad 11pro) the camera for QR scan does not rotate correct so it is very difficult to scan the QR code.

![image](https://user-images.githubusercontent.com/81565834/141259610-ea25960e-a60c-4b37-94a1-37a82caa0ff9.png)

**Comment by ihorkhomyak** [comment]
On iPad rotation is forbidden. Please check in new build(12)

**Comment by ihorkhomyak** [comment]
On iPad rotation is forbidden.

**Comment by kerstin-oppermann-tsi** [comment]
in Wallet 1.2.3(12) rotation on iPad is further possible
![image](https://user-images.githubusercontent.com/81565834/142200564-b0ff6ed4-4a68-49dc-a7d9-351f9c523ba9.png)
but I will set this issue to lower prio, investigate when other things in verifier and wallet are finished @ihorkhomyak
