### ISSUE TITLE
[iOS Verifier App] App Crash when Device is Offline

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#131]
## Describe the bug

1) If the WLAN in device setting is switched off (that is, there is no internet connection on device) than the app crashes when the "RELOAD" button is pressed. 

2) If the WLAN in device setting is left switched off for > 24 hr (that is, there is no internet connection on device for > 24 hr) than the app crashes at starting (the app cannot be started at all).

## Technical details
iOS Verifier 1.3.1 (4)
iPhone 8 plus v. Lutz, iOS 14.4

**Comment by kerstin-oppermann-tsi** [comment]
Rechecked on IPad 11 pro. The verifier crashes 

- during the start when devive is offline.
- when pressing reload after device was set to offline during verifier app is open

**Comment by kerstin-oppermann-tsi** [comment]
is fixed in 1.3.1.(14)
@RalicaY you can recheck when version is released to testers

**Comment by RalicaY** [comment]
@kerstin-oppermann-tsi yes, I confirm the successful retest with 1.3.1 (14) and 1.3.1.1 (15)
