### ISSUE TITLE
[iOS verifier] qr-code with invalid payload leads to white page

### ISSUE THREAD

**Issue by michawol** [eu-digital-green-certificates/dgca-verifier-app-ios#134]
## Describe the bug
Reading a qr-code with invalid payload show the Error-Message:
"Barcode-Fehler. Etwas ist schief gelaufen" as popup window
same qr-code can successful read by android verifierApp

## Expected behaviour
the qr-code must be successful read, and show the error:
Invald. Cryptiographic signature invalid" insiede VerifierApp

## Steps to reproduce the issue

1. open VerifierApp
2. scan the code

## Technical details
iPhone 7, IOS 15.3.1
VerifierApp 1.3.1(4)
![MISSING_NAM](https://user-images.githubusercontent.com/97519435/157691379-20b29a25-2fdb-478e-ae53-6ec3cf23238b.png)

**Comment by michawol** [comment]
https://user-images.githubusercontent.com/97519435/157853360-8420ee00-97b5-44ed-bff0-8afdc4292f13.mp4

**Comment by kerstin-oppermann-tsi** [comment]
Rechecked this issue, the behaviour is still open in 1.3.1(14) Message "Barcode-Fehler - Etwas ist schief gelaufen" appears.

In Android the "Cryptographic signature invalid" message is shown, that seems to be the correct behaviour.
![image](https://user-images.githubusercontent.com/81565834/160588482-1bae8634-0d0b-4334-a80f-4344568200f7.png)

**Comment by michawol** [comment]
Retest the qr-code:
iPhone 7, IOS 15.3.1
Version 1.3.1 (24) and Version 1.3.1.1 (25)

i got a white page
![Bildschirmfoto_2022-04-25_11-43-11](https://user-images.githubusercontent.com/97519435/165064372-23285e0a-2ab4-41c5-9e6c-33786af86000.png)

**Comment by kerstin-oppermann-tsi** [comment]
Same for me on iPad 11

**Comment by RalicaY** [comment]
Successfully retested, iOS Verifier 1.3.1(36)
