### ISSUE TITLE
[iOS Verifier] Local Delete Workflow for Expired Revocations on Verifier App does Not Start Automatically

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#137]
## Describe the bug

Local Delete Workflow for Expired Revocations on Verifier App does not start automatically even after more than 24 hours offline (internet switched off) although according to the specification ( (Verfier Workflow, Spec. Chapter 1.3 "Delete expired revocation entries") it should take place.

## Technical details

- Host Machine OS (Windows/Linux/Mac):

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY Could you please retest with 1.3.1 (20) . Hopefully it is fixed by the #136 fix
