### ISSUE TITLE
[iOS Verifier App] All Non Revoked Codes are Evaluated as Revoked

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#138]
## Describe the bug

iOS Verifier app evaluates all not revoked DCC Codes as revoked, incl. Codes from ACC Environment. The behavior was observed both for the Hash and Bloom Filter versions.

## Technical details

iOS Verifier  1.3.1 (24) (Bloom TST) und iOS Verifier 1.3.1.1 (25)

## Expected behavior
* Codes from other environments (i.e. with different signers) are evaluated as cryptographically invalid
* Codes that are not revoked and have valid signer within the environment should be shown as valid

**Comment by kerstin-oppermann-tsi** [comment]
@RalicaY Please recheck with 1.3.1(29) (hash) and 1.3.1(30) (bloom)

**Comment by RalicaY** [comment]
Retest was successful  iOS Verifier Versionen 1.3.1(29) hash und 1.3.1(30) bloom
