### ISSUE TITLE
[iOS Verifier App]Nullable Values in Verifieable Credentials Lead To Unscannable Code

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#139]
## Describe the bug

The following valid code with null-values in optional fields does not get scanned by the verifier app. Instead a pop-up window "Bar-Code Error" appears (see attached photo).

Attention: it is a valid code but with null values.

## Expected behaviour
The app should be able to scan the code.

## Technical Details:
Verifier App 1.3.1.1(33) Hash & iOS Verifier 1.3.1 (31) Bloom
![nullable_values](https://user-images.githubusercontent.com/76050122/165771190-e245e393-7d0b-4328-ae01-851a8cc06125.PNG)
![Uploading IMG_20220428_111223(1).jpg…]()

**Comment by ltranvan** [comment]
The same code scanned bei Android-Verifier bring an another message:
"X Invalid
  Time before issueance date"
  
Please: what ever, but the code is readable for the app and Android and IOS should brimg the same message but not different messages as in this case :-).

**Comment by RalicaY** [comment]
Retest failed: Issue persists iOS Verifier 1.3.1 (36)

**Comment by ltranvan** [comment]
tvt, 11.05.2022: 
The same code scanned bei Android-Verifier and  bring an another message, but 
at the end the JWT and not the verifiable Credential is noticed by the app and an error-message is displayed.
