### ISSUE TITLE
[iOS Verifier App] No Interactive Inquiry (Granting Consent) for Unknown Issuer Credentials 

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#140]
## Describe the bug
When we scan verifiable credentials. which were signed by unknown issuers (such that have not yet been onboarded on the gateway) no interactive inquiry is shown as to whether the user wants to add the issuer in the app's local issuers list.  Furthermore, a "Bar-Code Error" Pop up window is shown.

## Expected behaviour
An interactive inquiry is shown and the user is given the opportunity to grant or deny consent.

## Technical details
Verifier App 1.3.1.1(33) Hash & iOS Verifier 1.3.1 (31) Bloom
![dx-apr-22-e](https://user-images.githubusercontent.com/76050122/165772629-539066f2-b9e0-4047-8e7d-621203e2aa31.png)
![IMG_20220428_111223(1)](https://user-images.githubusercontent.com/76050122/165772659-bb5acc03-3b4d-4224-a591-d92bce401a5c.jpg)

**Comment by RalicaY** [comment]
Retest failed: iOS Verifier 1.3.1(36) --the interactive inquiry is shown but after pressing on grant no granting happens.  Instead -- the inquiry pop ip is shown again and again.  Expected bahaviour is: after pressing grant, the inquiry is not shown any more and the issuer is added to the local app's database

**Comment by RalicaY** [comment]
Retest failed: iOS 1.3.1 (38) -- when we grant consent the code is read and it all seems correct but after we restart the app and scan the code again -- consent is required again.  It seems the issuer was not persisted in the apps IssuersList Database although after granting consent the code was read.

**Comment by ltranvan** [comment]
@ihorkhomyak: Sorry in which IOS-Verifier-Version have you fixed this bug? The latest we have got is IOS-Verifier 1.3.1(42). Thanks!!!

**Comment by kerstin-oppermann-tsi** [comment]
@ltranvan provided the new version 1.3.1(43) and (44) to you

**Comment by ltranvan** [comment]
tvt, 11.05.2022: retest successfully carried out together with Hendrik.
