### ISSUE TITLE
[iOS Verifier App] Verifiable Credentials with Matching KID But False Public Key Data Are Accepted

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#141]
## Describe the bug
We scanned verifiable clredentials with matching KID but manipulated public key data so that the signature was no more valid for the issuer with this KID.  The app scanned these without any error.

## Expected behaviour
The app should recognize  that the credential has an invalid signature.
![81d947d2-d79d-40c9-be8c-633b965bfe06(2)](https://user-images.githubusercontent.com/76050122/165774753-fe1fbb0f-38fe-47ed-9c79-ede717360ad7.PNG)
![Screenshot from 2022-04-28 09-34-37](https://user-images.githubusercontent.com/76050122/165774777-dd2e68d3-1e96-43fb-9a3d-200a67f2bae2.png)

## Technical details
Verifier App 1.3.1.1(33) Hash & iOS Verifier 1.3.1 (31) Bloom

**Comment by PaulBallmann** [comment]
Copy of https://github.com/eu-digital-green-certificates/dgca-wallet-app-ios/issues/138

**Comment by RalicaY** [comment]
05.05.2022: Retest with iOS Verifier 1.3.1(34) was not successful. Actual result: "Barcode-Fehler"

**Comment by ltranvan** [comment]
tvt, 10.05.2022: Priority reduced from Medium to Low, because the described failed acception of the wrong Credential  is not occured anymore. Just only a not expected (consistent to Android) error messaged is now displayed.

**Comment by ltranvan** [comment]
tvt, 10.05.2022: retested successully by Ralica with IOS-version 1.3.1.1 (42) HL and 1.3.1 (38) BF.
