### ISSUE TITLE
"In case of a failed verification (RED), the app should only display the reason for the fail, including details such as the specific contents or technical details of the certificate that are preventing the successful verification

### ISSUE THREAD

**Issue by RalicaY** [eu-digital-green-certificates/dgca-verifier-app-ios#78]
## Describe the bug

Despite a failed verification, the verifier app shows the certificate data set, additionally to the reason for failure.

## Expected behaviour

In case of a failed verification (RED), the app should only display the reason for the fail including details such as the specific contents or technical details of the certificate that are preventing the successful verification.

## Steps to reproduce the issue

1. Open verifier app;
2. Scan a QR-Code for an invalid certificate.

## Technical details

iPhone 8 plus v. Lutz,  Model MQ8P2ZD/A, iOS 14.4

**Comment by yspreen** [comment]
As per @joerg-oppermann-tsi

**Comment by rebwalz** [comment]
bug is still open. should  be fixed in one of the next versions.

**Comment by yspreen** [comment]
We decided not to fix it since the logic to omit all non-error fields when there is some other error is a bit too much... how does Android handle this

**Comment by rebwalz** [comment]
see [#39](https://github.com/eu-digital-green-certificates/dgca-verifier-app-android/issues/39)

**Comment by yspreen** [comment]
Removing the label since it's not a "bug", as the behavior is expected but not according to the current specification.

Since the specification is inconsistent, we need to work that out before continuing work on this ticket

**Comment by azotlichid** [comment]
Verification seems to fail even on some valid certificates. Refusing to give the reason for failure will be disastrous, as several national authorities seem to rely on this implementation.

**Comment by RalicaY** [comment]
At the moment the iOS and Android Verifier approaches concerning the issue differ from each other -- the Android version displays only the reason for the fail, while the iOS version displays the complete payload as well.  

According to the specification -- only the Android version is compliant.

The iOS version shows more data, having the benefit that debugging is easier.
