### ISSUE TITLE
signercertificateStatus service returned empty array

### ISSUE THREAD

**Issue by tdinckaya** [eu-digital-green-certificates/dgca-verifier-app-ios#85]
Hello,

https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com/signercertificateStatus

**### This api service return empty array. Why ?**

![image](https://user-images.githubusercontent.com/44499170/120185793-57ed3100-c21b-11eb-9e42-09325011ad9b.png)

**Comment by yspreen** [comment]
Sadly it's the wrong repo. Please reopen here https://github.com/eu-digital-green-certificates/dgca-verifier-service
