### ISSUE TITLE
need to swap first name and last name

### ISSUE THREAD

**Issue by lcimaglia** [eu-digital-green-certificates/dgca-verifier-app-ios#90]
* Source File: https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/main/Sources/Models/HCert.swift
* Line(s): https://github.com/eu-digital-green-certificates/dgca-app-core-ios/blob/dce091b3f270e7128f4c0a53abd2f955c5134551/Sources/Models/HCert.swift#L268
* Question: We need to swap first name and last name to be displayed in our custom verifier app. At the moment this is not possible because the core library for ios only exposes the first name and last name as a single string. In general, unlike Android core library, the iOS core library does not provide access to all the HCert data but only to the ones used to create the view in the european verifier app, through the public var info. Is it possible to expose first name and last name as separate strings and in general to expose all the info about an HCert as in android core library?

**Comment by PaulBallmann** [comment]
Hello, please open the issue again in the core module. Once that is open, I will add the support for getting first and last name separately.
