### ISSUE TITLE
Evaluate and integrate CertLogic

### ISSUE THREAD

**Issue by joerg-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-ios#91]
https://github.com/advantagefse/json-logic-swift
together with the following test cases: 

https://github.com/ehn-digital-green-development/dgc-business-rules/blob/main/certlogic/javascript/src/test/test-certlogic.ts

https://github.com/ehn-digital-green-development/dgc-business-rules/blob/main/certlogic/javascript/src/test/test-js-dates.ts

**Comment by alexchornyi** [comment]
@joerg-oppermann-tsi  CertLogic now integrated in business_rules branch and will be merged in to main branch soon after testing.

**Comment by alexchornyi** [comment]
@joerg-oppermann-tsi Done
