### ISSUE TITLE
Is the trusted issuer list fetched from the correct source in debug builds?

### ISSUE THREAD

**Issue by peterk** [eu-digital-green-certificates/dgca-verifier-app-ios#97]
If I download and build the iOS verifier app will it get the real trusted issuer list? Testing some real issued QR-codes from Sweden and some of the test data QR codes yields "Cryptographic signature not valid". Right now it looks like the will fetch data from `https://dgca-verifier-service.cfapps.eu10.hana.ondemand.com` but there is not mention if this is the correct source?

**Comment by daniel-eder** [comment]
The apps in this GitHub organization are only templates that can be adapted or copied into the member state apps.
The member states are responsible for providing a trust list for their applications, as the EU does not provide a union-wide access point. Therefore the included URL only provides trust lists for testing purposes, not the production trust list.
