### ISSUE TITLE
If test result is positiv (DETECTED) the business rule check should display a red invalid status of the cert (instead of orange)

### ISSUE THREAD

**Issue by kerstin-oppermann-tsi** [eu-digital-green-certificates/dgca-verifier-app-ios#99]
If a test result is positiv the verifier should get an red invalid status because this should be recognized at first glance.

Actual status:
![image](https://user-images.githubusercontent.com/81565834/124888216-2fa0e100-dfd6-11eb-8359-f6dc39b0026f.png)

Expected status:
Invalid status

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi Can you please attach QR code for testing? Or send me directly to the mail.

**Comment by kerstin-oppermann-tsi** [comment]
![image](https://user-images.githubusercontent.com/81565834/124893269-ddae8a00-dfda-11eb-8752-45130aef81e8.png)
@alexchornyi  sorry I checked it again with iOS and it is red like before without BR rule checking. The issue ocurs only for Android. So you can ignore this for the moment. But this issue should be discussed with @Hendrik-Schmidt-Schierhorn-TSI  and @SchulzeStTSI how this should be handled by BRs or by hard coded error messages.

**Comment by alexchornyi** [comment]
@kerstin-oppermann-tsi Yes I double checked it and it's Red with fail result. Please make the task for Android and close this.

**Comment by kerstin-oppermann-tsi** [comment]
Issue exists only for Android.
